FROM python:3.7-alpine3.11

WORKDIR /usr/src/app/
COPY . ./

RUN pip3 install -r requirements.txt
RUN pip3 install pytest pytest-cov

ENV PYTHONPATH=.
ENV PYTHONUNBUFFERED=1
EXPOSE 5000

CMD pytest --cov=ApiGateway --cov-report term-missing